wip

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -17,88 +17,130 @@ env:
 
 jobs:
   sonar_qube:
-    runs-on: ubuntu-latest
-
-    services:
-      # Запуск SonarQube как сервиса
-      sonarqube:
-        image: sonarqube:latest
-        ports:
-          - 9000:9000
-        options: >-
-          --health-cmd "curl -f http://localhost:9000/api/system/status || exit 1"
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-
+    name: Build and analyze
+    runs-on: windows-latest
+    
     steps:
-      # 1. Чекаут кода
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      # 2. Установка .NET SDK
-      - name: Setup .NET
-        uses: actions/setup-dotnet@v3
+      - uses: actions/checkout@v4
         with:
-          dotnet-version: ${{ env.DOTNET_VERSION }}
-
-      # 3. Установка SonarScanner
-      - name: Install SonarScanner
-        run: dotnet tool install --global dotnet-sonarscanner
-
-      # 4. Ожидание готовности SonarQube
-      - name: Wait for SonarQube to be ready
+          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: 17
+          distribution: 'zulu' # Alternative distribution options are available.
+      - name: Cache SonarQube packages
+        uses: actions/cache@v4
+        with:
+          path: ~\.sonar\cache
+          key: ${{ runner.os }}-sonar
+          restore-keys: ${{ runner.os }}-sonar
+      - name: Cache SonarQube scanner
+        id: cache-sonar-scanner
+        uses: actions/cache@v4
+        with:
+          path: .\.sonar\scanner
+          key: ${{ runner.os }}-sonar-scanner
+          restore-keys: ${{ runner.os }}-sonar-scanner
+      - name: Install SonarQube scanner
+        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
+        shell: powershell
         run: |
-          for i in {1..30}; do
-            if curl -s http://localhost:9000/api/system/status | grep -q '"status":"UP"'; then
-              echo "SonarQube is up!"
-              break
-            fi
-            echo "Waiting for SonarQube... ($i/30)"
-            sleep 5
-          done
-          if [ $i -eq 30 ]; then
-            echo "SonarQube failed to start in time."
-            exit 1
-          fi
-
-      # 5. Восстановление зависимостей
-      - name: Restore
-        run: dotnet restore ./src/ProdMonitor/ProdMonitor.sln
-
-      # 6. Запуск SonarScanner
-      - name: Start SonarQube analysis
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          New-Item -Path .\.sonar\scanner -ItemType Directory
+          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
+      - name: Build and analyze
+        shell: powershell
         run: |
-          dotnet sonarscanner begin \
-            /k:"ProdMonitor" \
-            /d:sonar.host.url="http://localhost:9000" \
-            /d:sonar.token="$SONAR_TOKEN"
+          .\.sonar\scanner\dotnet-sonarscanner begin /k:"ProdMonitor" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"
+          dotnet build
+          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
 
-      # 7. Сборка проекта
-      - name: Build
-        run: dotnet build ./src/ProdMonitor/ProdMonitor.sln --configuration Release --no-restore
 
-      # 8. Завершение анализа SonarQube
-      - name: End SonarQube analysis
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"
 
-      # 9. Проверка Quality Gate
-      - name: Check Quality Gate
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: |
-          QUALITY_GATE_STATUS=$(curl -s -H "Authorization: Bearer $SONAR_TOKEN" "http://localhost:9000/api/qualitygates/project_status?projectKey=ProdMonitor" | grep -o '"status":"[^"]*"' | cut -d':' -f2 | tr -d '"')
-          echo "Quality Gate Status: $QUALITY_GATE_STATUS"
-          if [ "$QUALITY_GATE_STATUS" = "ERROR" ] || [ "$QUALITY_GATE_STATUS" = "WARN" ]; then
-            echo "Quality Gate failed. Aborting pipeline."
-            exit 1
-          else
-            echo "Quality Gate passed."
-          fi
+
+  # sonar_qube:
+  #   runs-on: ubuntu-latest
+
+  #   services:
+  #     # Запуск SonarQube как сервиса
+  #     sonarqube:
+  #       image: sonarqube:latest
+  #       ports:
+  #         - 9000:9000
+  #       options: >-
+  #         --health-cmd "curl -f http://localhost:9000/api/system/status || exit 1"
+  #         --health-interval 10s
+  #         --health-timeout 5s
+  #         --health-retries 5
+
+  #   steps:
+  #     # 1. Чекаут кода
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
+
+  #     # 2. Установка .NET SDK
+  #     - name: Setup .NET
+  #       uses: actions/setup-dotnet@v3
+  #       with:
+  #         dotnet-version: ${{ env.DOTNET_VERSION }}
+
+  #     # 3. Установка SonarScanner
+  #     - name: Install SonarScanner
+  #       run: dotnet tool install --global dotnet-sonarscanner
+
+  #     # 4. Ожидание готовности SonarQube
+  #     - name: Wait for SonarQube to be ready
+  #       run: |
+  #         for i in {1..30}; do
+  #           if curl -s http://localhost:9000/api/system/status | grep -q '"status":"UP"'; then
+  #             echo "SonarQube is up!"
+  #             break
+  #           fi
+  #           echo "Waiting for SonarQube... ($i/30)"
+  #           sleep 5
+  #         done
+  #         if [ $i -eq 30 ]; then
+  #           echo "SonarQube failed to start in time."
+  #           exit 1
+  #         fi
+
+  #     # 5. Восстановление зависимостей
+  #     - name: Restore
+  #       run: dotnet restore ./src/ProdMonitor/ProdMonitor.sln
+
+  #     # 6. Запуск SonarScanner
+  #     - name: Start SonarQube analysis
+  #       env:
+  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  #       run: |
+  #         dotnet sonarscanner begin \
+  #           /k:"ProdMonitor" \
+  #           /d:sonar.host.url="http://localhost:9000" \
+  #           /d:sonar.token="$SONAR_TOKEN"
+
+  #     # 7. Сборка проекта
+  #     - name: Build
+  #       run: dotnet build ./src/ProdMonitor/ProdMonitor.sln --configuration Release --no-restore
+
+  #     # 8. Завершение анализа SonarQube
+  #     - name: End SonarQube analysis
+  #       env:
+  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  #       run: dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"
+
+  #     # 9. Проверка Quality Gate
+  #     - name: Check Quality Gate
+  #       env:
+  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  #       run: |
+  #         QUALITY_GATE_STATUS=$(curl -s -H "Authorization: Bearer $SONAR_TOKEN" "http://localhost:9000/api/qualitygates/project_status?projectKey=ProdMonitor" | grep -o '"status":"[^"]*"' | cut -d':' -f2 | tr -d '"')
+  #         echo "Quality Gate Status: $QUALITY_GATE_STATUS"
+  #         if [ "$QUALITY_GATE_STATUS" = "ERROR" ] || [ "$QUALITY_GATE_STATUS" = "WARN" ]; then
+  #           echo "Quality Gate failed. Aborting pipeline."
+  #           exit 1
+  #         else
+  #           echo "Quality Gate passed."
+  #         fi
 
   build:
     runs-on: ubuntu-latest
