wip

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -14,6 +14,7 @@ env:
   TEST_EMAIL_2: ${{ secrets.TEST_EMAIL_2 }}
   TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
   TEST_PASSWORD_NEW: ${{ secrets.TEST_PASSWORD }}
+  
 
 jobs:
   build:
@@ -122,7 +123,6 @@ jobs:
     runs-on: ubuntu-latest
     needs: e2e_tests
 
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -156,3 +156,60 @@ jobs:
 
       - name: Run tests
         run: dotnet test ./src/ProdMonitor/ProdMonitor.BDDTests/ProdMonitor.BDDTests.csproj --configuration Release --no-restore --no-build --logger "console;verbosity=detailed"
+
+  sonar_qube:
+    runs-on: ubuntu-latest
+    needs: build
+
+    steps:
+    # 1. Чекаут кода
+    - name: Checkout repository
+      uses: actions/checkout@v4
+
+    # 2. Установка .NET SDK
+    - name: Setup .NET
+      uses: actions/setup-dotnet@v3
+      with:
+        dotnet-version: ${{ env.DOTNET_VERSION }}
+
+    # 3. Установка SonarScanner
+    - name: Install SonarScanner
+      run: dotnet tool install --global dotnet-sonarscanner
+
+    # 4. Восстановление зависимостей
+    - name: Restore
+      run: dotnet restore ./src/ProdMonitor/ProdMonitor.sln
+
+    # 5. Запуск SonarScanner
+    - name: Start SonarQube analysis
+      env:
+        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      run: |
+        dotnet sonarscanner begin \
+          /k:"ProdMonitor" \
+          /d:sonar.host.url="http://localhost:9000" \
+          /d:sonar.token="$SONAR_TOKEN"
+
+    # 6. Сборка проекта
+    - name: Build
+      run: dotnet build ./src/ProdMonitor/ProdMonitor.sln --configuration Release --no-restore
+
+    # 7. Завершение анализа SonarQube
+    - name: End SonarQube analysis
+      env:
+        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      run: dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"
+
+    # 8. Проверка Quality Gate
+    - name: Check Quality Gate
+      env:
+        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      run: |
+        QUALITY_GATE_STATUS=$(curl -s -H "Authorization: Bearer $SONAR_TOKEN" "http://localhost:9000/api/qualitygates/project_status?projectKey=ProdMonitor" | grep -o '"status":"[^"]*"' | cut -d':' -f2 | tr -d '"')
+        echo "Quality Gate Status: $QUALITY_GATE_STATUS"
+        if [ "$QUALITY_GATE_STATUS" = "ERROR" ] || [ "$QUALITY_GATE_STATUS" = "WARN" ]; then
+          echo "Quality Gate failed. Aborting pipeline."
+          exit 1
+        else
+          echo "Quality Gate passed."
+        fi
